// Generated by CoffeeScript 1.7.0
(function() {
  var BucketPlugin;

  module.exports = function(game, opts) {
    return new BucketPlugin(game, opts);
  };

  BucketPlugin = (function() {
    function BucketPlugin(game, opts) {
      var _ref;
      this.game = game;
      this.opts = opts;
      this.registry = (function() {
        if ((_ref = this.game.plugins.get('voxel-registry')) != null) {
          return _ref;
        } else {
          throw new Error('voxel-bucket requires voxel-registry plugin');
        }
      }).call(this);
      if (opts.fluids == null) {
        opts.fluids = ['water', 'milk', 'lava'];
      }
      if (opts.registerBlocks == null) {
        opts.registerBlocks = true;
      }
      if (opts.registerItems == null) {
        opts.registerItems = true;
      }
      this.enable();
    }

    BucketPlugin.prototype.enable = function() {
      var fluid, ucfirst, _i, _len, _ref, _results;
      if (this.opts.registerItems) {
        this.registry.registerItem('bucket', {
          itemTexture: 'i/bucket_empty'
        });
        ucfirst = function(s) {
          return s.substr(0, 1).toUpperCase() + s.substring(1);
        };
        _ref = this.opts.fluids;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          fluid = _ref[_i];
          _results.push(this.registry.registerItem("bucket" + (ucfirst(fluid)), {
            itemTexture: "i/bucket_" + fluid,
            fluid: fluid,
            containerItem: 'bucket'
          }));
        }
        return _results;
      }
    };

    BucketPlugin.prototype.disable = function() {};

    return BucketPlugin;

  })();

}).call(this);
